import express from "express";
import { getProducts, addProduct, updateProduct, toggleProduct, deleteProduct } from "../controllers/productController.js";
import requireAdmin from "../middleware/requireAdmin.js";
const router = express.Router();
router.get("/", getProducts);
router.post("/", requireAdmin, addProduct);
router.put("/:id", requireAdmin, updateProduct);
router.patch("/:id/toggle", requireAdmin, toggleProduct);
router.delete("/:id", requireAdmin, deleteProduct);
export default router;
